services:
  server:
    image: reeoss/paperclipai-paperclip:latest
    user: root
    ports:
      - "3100:3100"
    environment:
      - PORT=3100
      - PAPERCLIP_PUBLIC_URL=${PAPERCLIP_PUBLIC_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DATABASE_URL=postgresql://root:password@db:5432/paperclip
      - SERVE_UI=true
    volumes:
      - ./config:/paperclip/instances
    restart: always
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=4KbpR.YK87ju__A*f6ebqMM8NAuPRshu-_oaHvtV
      - POSTGRES_DB=paperclip
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
